language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode
  - jruby-20mode
  - rbx-19mode
  - rbx-20mode
  - ruby-head

jdk:
  - openjdk7
  - openjdk6

matrix:
  exclude:
    - rvm: 1.9.3
      jdk: openjdk7
    - rvm: 2.0.0
      jdk: openjdk7
    - rvm: 2.1.0
      jdk: openjdk7
    - rvm: ruby-head
      jdk: openjdk7
    - rvm: rbx-19mode
      jdk: openjdk7
    - rvm: rbx-20mode
      jdk: openjdk7
