language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - jruby-19mode
  - jruby-20mode
  - rbx
  - ruby-head

jdk:
  - openjdk7
  - openjdk6
  - oraclejdk8

matrix:
  exclude:
    - rvm: 1.9.3
      jdk: openjdk6
    - rvm: 1.9.3
      jdk: oraclejdk8

    - rvm: 2.0.0
      jdk: openjdk6
    - rvm: 2.0.0
      jdk: oraclejdk8

    - rvm: 2.1.0
      jdk: openjdk6
    - rvm: 2.1.0
      jdk: oraclejdk8

    - rvm: 2.1.1
      jdk: openjdk6
    - rvm: 2.1.1
      jdk: oraclejdk8

    - rvm: ruby-head
      jdk: openjdk6
    - rvm: ruby-head
      jdk: oraclejdk8

    - rvm: rbx
      jdk: openjdk6
    - rvm: rbx
      jdk: oraclejdk8
